CREATE WAREHOUSE IF NOT EXISTS CAPSTONE_WH WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE DATABASE IF NOT EXISTS CAPSTONE_DB;
CREATE SCHEMA IF NOT EXISTS CAPSTONE_DB.PUBLIC;
USE WAREHOUSE CAPSTONE_WH;
USE DATABASE CAPSTONE_DB;
CREATE STAGE IF NOT EXISTS CAPSTONE_STAGE;
CREATE OR REPLACE TABLE GOLD_STORE_HOUR (
  store_id STRING,
  trade_date DATE,
  hour INT,
  counter_status STRING,
  footfall INT,
  _source_file STRING,
  _ingested_at TIMESTAMP_NTZ,
  sensor_ok BOOLEAN,
  bills INT,
  revenue DOUBLE,
  city STRING,
  format STRING,
  conversion_rate DOUBLE
);

COPY INTO GOLD_STORE_HOUR
FROM @CAPSTONE_STAGE
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 NULL_IF=('','NULL'));

COPY INTO GOLD_STORE_HOUR
FROM @CAPSTONE_STAGE
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 NULL_IF=('','NULL'));
SELECT hour, ROUND(SUM(bills)/NULLIF(SUM(footfall),0), 4) AS conversion_rate
FROM GOLD_STORE_HOUR WHERE sensor_ok
GROUP BY hour ORDER BY conversion_rate ASC LIMIT 3;